project_id = "kptrzskoktsveztkbhhc"

[functions.generate-access-code]
verify_jwt = false

[functions.register-access-code]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-daily-reminders]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.delete-user-data]
verify_jwt = true

[functions.public-config]
verify_jwt = false

[functions.cleanup-old-location-data]
verify_jwt = false
