project_id = "kptrzskoktsveztkbhhc"

[functions.generate-access-code]
verify_jwt = false

[functions.register-access-code]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-daily-reminders]
verify_jwt = false
